"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Icon from "./Icons";
import ModelModePicker from "./ModelModePicker";
import OldMikeAssistControl, { OldMikeAssistGroupControl } from "./OldMikeAssistControl";
import type { ClaimLedgerEntry, HumanVerificationState, RequirementCategory, RequirementStatus } from "@/lib/journal-submission-contract";
import type { ModelModeProfile } from "@/lib/model-mode-contract";

type SourceDocument = { documentVersionId: string; logicalId: string; versionNumber: number; contentHash: string; title: string; stageDetail: string };
type RequirementRule = { category: RequirementCategory; rule: string; applicable: boolean };
type FactualFit = { category: RequirementCategory; status: RequirementStatus; evidence: string; remediation: string; risk: string };
type HeuristicFit = { dimension: string; fit: "STRONG" | "POSSIBLE" | "WEAK" | "UNKNOWN"; rationale: string; uncertainty: string };
type Analysis = { analysisDocumentVersionId: string; logicalId: string; versionNumber: number; title: string; contentHash: string; sourceDocumentVersionId: string; sourceContentHash: string; targetJournal: { journalName: string; publisherName: string; articleType: string }; officialSource: { sourceUrl: string; authorityClass: "PUBLISHER" | "JOURNAL"; checkedAt: string; effectiveDate: string | null; sourceHash: string; extractionStatus: string; humanVerificationState: HumanVerificationState }; requirements: RequirementRule[]; factualFit: FactualFit[]; heuristicFit: HeuristicFit[]; coverLetterDraft: string; claimLedger: ClaimLedgerEntry[]; uncertainties: string[]; factualHeuristicSeparated: true; appendOnly: true };
type CoverLetter = { coverLetterDocumentVersionId: string; logicalId: string; versionNumber: number; title: string; contentHash: string; analysisDocumentVersionId: string; body: string; claimLedger: ClaimLedgerEntry[]; editRationale: string; diff: Array<{ paragraphId: string; original: string; revised: string; rationale: string; risk: string }>; humanGate: { status: "REQUIRED" | "APPROVED"; id: string | null }; appendOnly: true; sourceOverwritten: false };
type Workspace = { contractVersion: string; sources: SourceDocument[]; analyses: Analysis[]; coverLetters: CoverLetter[]; finalizedPackages: Array<{ submissionPackageVersionId: string; versionNumber: number; contentHash: string; title: string }> };

const categories: Array<{ id: RequirementCategory; label: string }> = [
  { id: "ARTICLE_TYPE", label: "文章類型" }, { id: "TITLE_ABSTRACT_KEYWORDS", label: "標題、摘要與關鍵字" }, { id: "SECTION_ORDER", label: "章節順序" },
  { id: "WORD_LIMITS", label: "字數限制" }, { id: "REFERENCES_STYLE", label: "參考文獻與格式" }, { id: "FIGURES_TABLES_SUPPLEMENTS", label: "圖、表與補充資料" },
  { id: "REPORTING_GUIDELINE", label: "報告指引" }, { id: "ETHICS_CONSENT", label: "倫理與同意" }, { id: "DATA_CODE_AVAILABILITY", label: "資料與程式可用性" },
  { id: "FUNDING_CONFLICTS", label: "經費與利益衝突" }, { id: "AUTHOR_CONTRIBUTIONS", label: "作者貢獻" }, { id: "ORCID", label: "ORCID" }, { id: "FILE_PACKAGE_REQUIREMENTS", label: "檔案與投稿包" },
];
const labels = Object.fromEntries(categories.map((item) => [item.id, item.label])) as Record<RequirementCategory, string>;
const statusLabels: Record<RequirementStatus, string> = { PASS: "符合", FAIL: "不符合", UNKNOWN: "未知", NOT_APPLICABLE: "不適用" };
const initialRules: RequirementRule[] = categories.map((item) => ({ category: item.id, rule: `${item.label}尚待依官方來源逐項輸入與人工核對。`, applicable: true }));

function requestKey(prefix: string) { return `${prefix}:${crypto.randomUUID()}`; }
async function hash(value: unknown) { const bytes = new TextEncoder().encode(JSON.stringify(value)); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join(""); }

export default function JournalSubmissionStudio({ projectId }: { projectId: string }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [sourceId, setSourceId] = useState(""); const [journalName, setJournalName] = useState(""); const [publisherName, setPublisherName] = useState(""); const [articleType, setArticleType] = useState("Research Article"); const [sourceUrl, setSourceUrl] = useState(""); const [effectiveDate, setEffectiveDate] = useState(""); const [sourceVerified, setSourceVerified] = useState(false); const [rules, setRules] = useState<RequirementRule[]>(initialRules);
  const [activeAnalysisId, setActiveAnalysisId] = useState(""); const [activeCoverId, setActiveCoverId] = useState(""); const [coverBody, setCoverBody] = useState(""); const [editRationale, setEditRationale] = useState(""); const [acceptedUnknowns, setAcceptedUnknowns] = useState<Set<RequirementCategory>>(new Set()); const [approvalRationale, setApprovalRationale] = useState(""); const [approvalConfirmed, setApprovalConfirmed] = useState(false);
  const [modeProfile, setModeProfile] = useState<ModelModeProfile>("AUTO");
  const source = workspace?.sources.find((item) => item.documentVersionId === sourceId) || null;
  const analysis = useMemo(() => workspace?.analyses.find((item) => item.analysisDocumentVersionId === activeAnalysisId) || workspace?.analyses[0] || null, [workspace, activeAnalysisId]);
  const coversForAnalysis = useMemo(() => workspace?.coverLetters.filter((item) => item.analysisDocumentVersionId === analysis?.analysisDocumentVersionId) || [], [workspace, analysis]);
  const cover = useMemo(() => coversForAnalysis.find((item) => item.coverLetterDocumentVersionId === activeCoverId) || coversForAnalysis[0] || null, [coversForAnalysis, activeCoverId]);
  const analysisVersion = Math.max(0, ...(workspace?.analyses.filter((item) => item.logicalId === "m04-submission-analysis-main").map((item) => item.versionNumber) || [0]));
  const coverVersion = Math.max(0, ...(workspace?.coverLetters.filter((item) => item.logicalId === "m04-cover-letter-main").map((item) => item.versionNumber) || [0]));
  const packageVersion = Math.max(0, ...(workspace?.finalizedPackages.map((item) => item.versionNumber) || [0]));
  const blockingFails = analysis?.factualFit.filter((item) => item.status === "FAIL") || [];
  const blockingUnknowns = analysis?.factualFit.filter((item) => item.status === "UNKNOWN" && !acceptedUnknowns.has(item.category)) || [];

  async function load() {
    setLoading(true);
    try { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/journal-submission`, { cache: "no-store" }); const data = await response.json() as { ok?: boolean; workspace?: Workspace; error?: string }; if (!response.ok || !data.ok || !data.workspace) throw new Error(data.error || "無法載入投稿工作室。"); setWorkspace(data.workspace); setSourceId((current) => current || data.workspace?.sources[0]?.documentVersionId || ""); setActiveAnalysisId((current) => current || data.workspace?.analyses[0]?.analysisDocumentVersionId || ""); setActiveCoverId((current) => current || data.workspace?.coverLetters[0]?.coverLetterDocumentVersionId || ""); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "無法載入投稿工作室。"); } finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, [projectId]);
  useEffect(() => { if (analysis) { setCoverBody(cover?.body || analysis.coverLetterDraft); setAcceptedUnknowns(new Set()); } }, [analysis?.analysisDocumentVersionId, cover?.coverLetterDocumentVersionId]);

  async function post(body: Record<string, unknown>) { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/journal-submission`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json() as { ok?: boolean; error?: string; [key: string]: unknown }; if (!response.ok || !data.ok) throw new Error(data.error || "操作未通過固定投稿契約。"); return data; }
  function updateRule(category: RequirementCategory, patch: Partial<RequirementRule>) { setRules((current) => current.map((item) => item.category === category ? { ...item, ...patch } : item)); }

  async function runCheck(event: FormEvent) {
    event.preventDefault(); if (!source) return; setBusy("check"); setError(""); setNotice("");
    try { const officialSource = { sourceUrl, authorityClass: "JOURNAL", checkedAt: new Date().toISOString(), effectiveDate: effectiveDate || null, sourceHash: await hash({ sourceUrl, effectiveDate: effectiveDate || null, rules }), extractionStatus: "MANUAL_ENTRY", humanVerificationState: sourceVerified ? "VERIFIED" : "UNVERIFIED" }; const data = await post({ operation: "RUN_SUBMISSION_CHECK", idempotencyKey: requestKey("m04-check"), logicalId: "m04-submission-analysis-main", expectedVersion: analysisVersion, title: `${journalName} 投稿要求核對`, sourceDocumentVersionId: source.documentVersionId, sourceContentHash: source.contentHash, targetJournal: { journalName, publisherName, articleType }, officialSource, requirements: rules, projectFacts: [], integrityConfirmed: true, modeProfile }); const next = data.analysis as Analysis; await load(); setActiveAnalysisId(next.analysisDocumentVersionId); setNotice("已建立 append-only 投稿核對版本；事實符合度與啟發式契合度已分開呈現。"); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "投稿核對未完成。"); } finally { setBusy(""); }
  }
  async function saveCover() { if (!analysis) return; setBusy("cover"); setError(""); setNotice(""); try { const data = await post({ operation: "SAVE_COVER_LETTER", idempotencyKey: requestKey("m04-cover"), analysisDocumentVersionId: analysis.analysisDocumentVersionId, analysisContentHash: analysis.contentHash, logicalId: "m04-cover-letter-main", expectedVersion: coverVersion, title: `${analysis.targetJournal.journalName} Cover Letter`, coverLetterBody: coverBody, claimLedger: analysis.claimLedger, editRationale }); const saved = data.coverLetter as CoverLetter; await load(); setActiveCoverId(saved.coverLetterDocumentVersionId); setNotice("Cover Letter 已新增為 append-only 版本；原稿與先前版本均未覆寫。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cover Letter 未儲存。"); } finally { setBusy(""); } }
  async function approve() { if (!analysis || !cover) return; setBusy("approve"); setError(""); setNotice(""); try { await post({ operation: "APPROVE_SUBMISSION", idempotencyKey: requestKey("m04-approve"), analysisDocumentVersionId: analysis.analysisDocumentVersionId, analysisContentHash: analysis.contentHash, coverLetterDocumentVersionId: cover.coverLetterDocumentVersionId, coverLetterContentHash: cover.contentHash, acceptedUnknowns: [...acceptedUnknowns], rationale: approvalRationale }); setApprovalConfirmed(false); await load(); setNotice("Human Gate 已綁定精確要求核對與 Cover Letter 內容雜湊。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Human Gate 未完成。"); } finally { setBusy(""); } }
  async function finalize() { if (!analysis || !cover?.humanGate.id) return; setBusy("finalize"); setError(""); setNotice(""); try { await post({ operation: "FINALIZE_SUBMISSION", idempotencyKey: requestKey("m04-finalize"), analysisDocumentVersionId: analysis.analysisDocumentVersionId, analysisContentHash: analysis.contentHash, coverLetterDocumentVersionId: cover.coverLetterDocumentVersionId, coverLetterContentHash: cover.contentHash, humanGateId: cover.humanGate.id, targetLogicalId: "m04-submission-package-main", expectedVersion: packageVersion, title: `${analysis.targetJournal.journalName} 投稿包` }); await load(); setNotice("投稿包已新增至正式文件版本；來源與既有版本保持不變。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "投稿包未完成。"); } finally { setBusy(""); } }

  if (loading) return <section className="v13-panel m04-studio" aria-busy="true"><p>正在載入投稿工作室…</p></section>;
  return <section className="v13-panel m04-studio" aria-labelledby="m04-title">
    <div className="v13-panel-head"><div><p className="section-kicker">M04 · 期刊投稿工作室</p><h2 id="m04-title">期刊投稿工作室</h2></div><p className="v13-panel-note">官方要求核對、期刊契合與 Cover Letter，全部綁定固定稿件版本。</p></div>
    <ModelModePicker operation="JOURNAL_SUBMISSION" value={modeProfile} onChange={setModeProfile} testId="m04-model-mode" />
    <div className="m04-notice">老麥不虛構錄取機率、影響因子、期刊規則或研究事實。官方來源只有經人工核對後才能標記為已驗證；正式推進必須通過 Human Gate。</div>
    {error && <div className="v13-error" role="alert">{error}</div>}{notice && <div className="v13-success" role="status">{notice}</div>}
    <form className="m04-setup" onSubmit={runCheck}>
      <section><h3>固定稿件與目標期刊</h3><label>稿件版本<select data-testid="m04-source" value={sourceId} onChange={(event) => setSourceId(event.target.value)} required><option value="">請選擇</option>{workspace?.sources.map((item) => <option key={item.documentVersionId} value={item.documentVersionId}>{item.title} · v{item.versionNumber}</option>)}</select></label><div className="m04-three"><label>期刊名稱<input value={journalName} onChange={(event) => setJournalName(event.target.value)} maxLength={240} required /></label><label>出版社<input value={publisherName} onChange={(event) => setPublisherName(event.target.value)} maxLength={240} required /></label><label>文章類型<input value={articleType} onChange={(event) => setArticleType(event.target.value)} maxLength={160} required /></label></div><OldMikeAssistGroupControl projectId={projectId} surface="M04_TARGET_JOURNAL" groupId="m04-target-journal" value={{ journalName, publisherName, articleType }} modeProfile={modeProfile} onApply={(value) => { setJournalName(value.journalName); setPublisherName(value.publisherName); setArticleType(value.articleType); }} /><label>官方要求來源（HTTPS）<input type="url" value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://…" maxLength={2000} required /></label><div className="m04-three"><label>生效日期（未知可留空）<input type="date" value={effectiveDate} onChange={(event) => setEffectiveDate(event.target.value)} /></label><label className="m04-check"><input type="checkbox" checked={sourceVerified} onChange={(event) => setSourceVerified(event.target.checked)} />我已人工核對此官方來源與以下規則</label><span className={`v13-badge ${sourceVerified ? "approved" : "required"}`}>{sourceVerified ? "VERIFIED" : "UNVERIFIED"}</span></div></section>
      <section className="m04-matrix"><div><h3>官方要求矩陣</h3><p>本機動作不會瀏覽來源；請輸入已取得的官方規則，未核對項目維持 UNKNOWN。</p></div>{rules.map((item) => <article key={item.category}><label><span>{labels[item.category]}</span><textarea value={item.rule} onChange={(event) => updateRule(item.category, { rule: event.target.value })} rows={2} maxLength={3000} required /></label><label className="m04-check"><input type="checkbox" checked={item.applicable} onChange={(event) => updateRule(item.category, { applicable: event.target.checked })} />適用</label></article>)}</section>
      <button type="submit" className="primary-button" data-testid="m04-run-check" disabled={busy !== "" || !source}>{busy === "check" ? "核對中…" : "建立投稿核對版本"}</button>
    </form>

    <section className="m04-results" aria-labelledby="m04-results-title"><div className="m03-section-head"><div><p className="section-kicker">事實契合 ≠ 經驗契合</p><h3 id="m04-results-title">要求證據與期刊契合</h3></div>{workspace?.analyses.length ? <select aria-label="投稿核對版本" value={analysis?.analysisDocumentVersionId || ""} onChange={(event) => setActiveAnalysisId(event.target.value)}>{workspace.analyses.map((item) => <option key={item.analysisDocumentVersionId} value={item.analysisDocumentVersionId}>{item.title} · v{item.versionNumber}</option>)}</select> : null}</div>
      {!analysis ? <div className="v13-empty"><Icon name="file" /><div><strong>尚無投稿核對版本</strong><p>選擇固定稿件、輸入官方要求並明確標示人工驗證狀態。</p></div></div> : <div className="m04-result-grid"><div><h4>已驗證事實符合度</h4><ol className="m04-factual">{analysis.factualFit.map((item) => <li key={item.category} className={`status-${item.status.toLowerCase()}`}><header><strong>{labels[item.category]}</strong><span>{statusLabels[item.status]}</span></header><p><b>證據：</b>{item.evidence || "無"}</p><p><b>補救：</b>{item.remediation || "無"}</p><p><b>風險：</b>{item.risk || "無"}</p>{item.status === "UNKNOWN" && <label className="m04-check"><input type="checkbox" checked={acceptedUnknowns.has(item.category)} onChange={(event) => setAcceptedUnknowns((current) => { const next = new Set(current); if (event.target.checked) next.add(item.category); else next.delete(item.category); return next; })} />研究者明確接受此 UNKNOWN，並保留風險紀錄</label>}</li>)}</ol></div><div><h4>啟發式契合（非錄取預測）</h4><ul className="m04-heuristic">{analysis.heuristicFit.map((item) => <li key={item.dimension}><strong>{item.dimension} · {item.fit}</strong><p>{item.rationale}</p><small>{item.uncertainty}</small></li>)}</ul><div className="m04-uncertainty"><strong>仍待確認</strong>{analysis.uncertainties.map((item) => <p key={item}>{item}</p>)}</div></div></div>}
    </section>

    {analysis && <section className="m04-cover" aria-labelledby="m04-cover-title"><div className="m03-section-head"><div><p className="section-kicker">僅事實 · 僅附加</p><h3 id="m04-cover-title">Cover Letter 與主張帳本</h3></div>{coversForAnalysis.length ? <select aria-label="Cover Letter 版本" value={cover?.coverLetterDocumentVersionId || ""} onChange={(event) => setActiveCoverId(event.target.value)}>{coversForAnalysis.map((item) => <option key={item.coverLetterDocumentVersionId} value={item.coverLetterDocumentVersionId}>v{item.versionNumber} · {item.title}</option>)}</select> : null}</div><div className="m04-cover-grid"><label>可編輯 Cover Letter<textarea data-testid="m04-cover-body" value={coverBody} onChange={(event) => setCoverBody(event.target.value)} rows={16} maxLength={24000} /></label><div><h4>主張帳本</h4>{analysis.claimLedger.length ? <ol>{analysis.claimLedger.map((claim) => <li key={claim.claimId}><strong>{claim.supportKind}</strong><p>{claim.claimText}</p><small>{claim.risk}</small></li>)}</ol> : <p>此草稿沒有可安全使用的已綁定主張；請勿自行補入未驗證的新穎性、結果、倫理、經費或編輯姓名。</p>}</div></div><OldMikeAssistControl projectId={projectId} surface="M04_COVER_BODY" targetId="coverBody" currentValue={coverBody} modeProfile={modeProfile} onApply={(value) => setCoverBody(value)} /><label>修改理由<textarea value={editRationale} onChange={(event) => setEditRationale(event.target.value)} rows={3} maxLength={2000} /></label><button type="button" className="primary-button" data-testid="m04-save-cover" onClick={() => void saveCover()} disabled={busy !== "" || !coverBody.trim() || editRationale.trim().length < 8}>{busy === "cover" ? "儲存中…" : "新增 Cover Letter 版本"}</button>
      {cover && <div className="m04-diff"><h4>逐段原文／修改後／理由／風險</h4>{cover.diff.map((item) => <article key={item.paragraphId}><code>{item.paragraphId}</code><div><span><b>原文</b>{item.original || "（空白）"}</span><span><b>修改後</b>{item.revised || "（空白）"}</span></div><p><b>理由：</b>{item.rationale}</p><p><b>風險：</b>{item.risk}</p></article>)}</div>}
    </section>}

    {analysis && cover && <section className="m04-human-gate" aria-labelledby="m04-gate-title"><div><p className="section-kicker">文件釋出 · 精確雜湊</p><h3 id="m04-gate-title">Human Gate 與正式投稿包</h3><p>FINALIZE 只有在官方來源已人工驗證、FAIL 已排除、UNKNOWN 已解決或明確接受，且 Human Gate 綁定此 Cover Letter 雜湊時才可進行。</p><div className="m04-gate-status"><span>FAIL {blockingFails.length}</span><span>未接受 UNKNOWN {blockingUnknowns.length}</span><span>{cover.humanGate.status}</span></div></div>{cover.humanGate.status === "REQUIRED" ? <div><label>核准理由<textarea aria-label="投稿核准理由" value={approvalRationale} onChange={(event) => setApprovalRationale(event.target.value)} rows={4} maxLength={2000} /></label><label className="m04-check"><input type="checkbox" checked={approvalConfirmed} onChange={(event) => setApprovalConfirmed(event.target.checked)} />我已核對稿件、官方要求、主張帳本、未知事項與精確內容版本。</label><button type="button" className="primary-button" onClick={() => void approve()} disabled={busy !== "" || !approvalConfirmed || approvalRationale.trim().length < 8 || blockingFails.length > 0 || blockingUnknowns.length > 0}>{busy === "approve" ? "核准中…" : "核准此固定投稿版本"}</button></div> : <div><p className="m04-approved"><Icon name="shield" size={18} />此版本已通過 Human Gate。</p><button type="button" className="primary-button" onClick={() => void finalize()} disabled={busy !== ""}>{busy === "finalize" ? "建立中…" : "新增至正式投稿包（不覆寫）"}</button></div>}</section>}
  </section>;
}
