"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Icon from "./Icons";
import ModelModePicker from "./ModelModePicker";
import { OldMikeAssistGroupControl } from "./OldMikeAssistControl";
import type { ModelModeProfile } from "@/lib/model-mode-contract";
import type { BudgetCategory, GuidanceFocus, ProposalDraft, ProposalMode, RequirementStatus } from "@/lib/proposal-studio-contract";

type SourceDocument = { documentVersionId: string; logicalId: string; versionNumber: number; contentHash: string; title: string; stageDetail: string };
type ProposalVersion = { documentVersionId: string; logicalId: string; versionNumber: number; title: string; contentHash: string; createdAt: string; proposal: ProposalDraft; validation: { sourceFreshness: "CURRENT" | "STALE" | "UNKNOWN"; factualPass: number; factualFail: number; factualUnknown: number; factualNa: number; totalTwd: number; unresolvedCount: number }; appendOnly: true; sourceOverwritten: false; humanGate: { status: "REQUIRED" | "APPROVED"; id: string | null } };
type Workspace = { contractVersion: string; modes: readonly ProposalMode[]; sources: SourceDocument[]; proposals: ProposalVersion[]; providerState: "DISABLED_LOCAL_FIXTURE_ONLY" | "ENABLED_CHAT_COMPLETIONS"; onlineSubmission: false };

const requirements: Record<ProposalMode, Array<{ category: string; label: string }>> = {
  NSTC_RESEARCH: [
    ["CALL_AND_PROGRAM", "徵件與計畫別"], ["ELIGIBILITY", "申請資格"], ["CM03_NARRATIVE", "CM03 式研究敘事"], ["BILINGUAL_ABSTRACT", "中英文摘要"], ["PRELIMINARY_EVIDENCE", "初步證據"], ["METHODS_AND_FEASIBILITY", "方法與可行性"], ["ETHICS_PRIVACY_DATA", "倫理、隱私與資料"], ["WORK_PLAN_AND_OUTPUTS", "工作計畫與產出"], ["TEAM_AND_RESOURCES", "團隊與資源"], ["BUDGET_AND_JUSTIFICATION", "預算與理由"], ["ATTACHMENTS", "附件"], ["SUBMISSION_WINDOW", "送件期間"],
  ].map(([category, label]) => ({ category, label })),
  MOE_TEACHING_PRACTICE: [
    ["CALL_AND_PROGRAM", "徵件與計畫別"], ["ELIGIBILITY", "申請資格"], ["TEACHING_PROBLEM_AND_CONTEXT", "教學問題與脈絡"], ["INTERVENTION_AND_DESIGN", "介入與設計"], ["LEARNING_OUTCOMES", "學習成效"], ["DATA_AND_EVALUATION", "資料與評量"], ["RESEARCH_ETHICS", "研究倫理"], ["IMPLEMENTATION_FIDELITY", "實施忠實度"], ["TEACHING_ARTIFACTS_AND_REFLECTION", "教學產物與反思"], ["WORK_PLAN_AND_OUTPUTS", "工作計畫與產出"], ["BUDGET_AND_JUSTIFICATION", "預算與理由"], ["ATTACHMENTS_AND_SUBMISSION_WINDOW", "附件與送件期間"],
  ].map(([category, label]) => ({ category, label })),
};
const statusLabels: Record<RequirementStatus, string> = { PASS: "符合", FAIL: "不符合", UNKNOWN: "未知", NA: "不適用" };
const modeLabels: Record<ProposalMode, string> = { NSTC_RESEARCH: "NSTC 研究計畫", MOE_TEACHING_PRACTICE: "教育部教學實踐研究計畫" };
const focusLabels: Record<GuidanceFocus, string> = { STRUCTURE: "結構", METHOD_FEASIBILITY: "方法與可行性", BUDGET_JUSTIFICATION: "預算與理由", RISK_AND_ALTERNATIVES: "風險與替代方案" };
type GuidanceSuggestion = { suggestionId: string; focus: GuidanceFocus; explanation: string; risk: string; action: string };

type FormState = {
  mode: ProposalMode; sourceId: string; programName: string; effectiveYear: string; sourceUrl: string; retrievedDate: string; sourceVerified: boolean;
  titleZhTw: string; titleEn: string; abstractZhTw: string; abstractEn: string; keywordsZhTw: string; keywordsEn: string;
  problem: string; background: string; literatureGap: string; aims: string; questions: string; hypotheses: string; innovation: string; significance: string; impact: string; methods: string; sample: string; data: string; analysis: string; ethics: string; privacy: string; risks: string; alternatives: string;
  nstcNarrative: string; preliminaryEvidence: string; feasibility: string; expectedOutputs: string;
  courseContext: string; teachingProblem: string; intervention: string; learningOutcomes: string; evaluationDesign: string; implementationFidelity: string; teachingArtifacts: string; reflectionPlan: string;
  workPackageTitle: string; workPackageObjective: string; workPackageMethods: string; startMonth: string; endMonth: string; milestone: string; milestoneMonth: string; kpiMeasure: string; kpiTarget: string; kpiEvidence: string;
  teamRole: string; teamResponsibility: string; teamContribution: string; resources: string;
  budgetCategory: BudgetCategory; budgetUnit: string; budgetQuantity: string; budgetUnitCost: string; budgetJustification: string; budgetRuleStatus: RequirementStatus;
  attachmentStatus: RequirementStatus; unresolvedIssues: string; approvalRationale: string; approvalConfirmed: boolean;
};

function initialForm(): FormState {
  const today = new Date().toISOString().slice(0, 10); const year = String(new Date().getUTCFullYear());
  return { mode: "NSTC_RESEARCH", sourceId: "", programName: "請依當年度官方來源填寫", effectiveYear: year, sourceUrl: "https://official.example.invalid/synthetic-fixture", retrievedDate: today, sourceVerified: false, titleZhTw: "待研究者填寫的合成計畫標題", titleEn: "Synthetic proposal title pending researcher review", abstractZhTw: "這是本機合成草稿，所有內容與年度規則都待研究者依官方來源核對。", abstractEn: "This is a local synthetic draft. All content and annual rules require researcher verification.", keywordsZhTw: "合成範例\n待核對", keywordsEn: "synthetic fixture\npending verification", problem: "待研究者界定的問題。", background: "待研究者補充的背景。", literatureGap: "待證據支持的文獻缺口。", aims: "建立可驗證的研究目標。", questions: "研究問題尚待人工確認。", hypotheses: "假設尚待人工確認。", innovation: "創新性尚待正式證據支持。", significance: "研究重要性尚待人工核對。", impact: "預期影響尚待人工核對。", methods: "方法流程尚待研究者完整設計。", sample: "樣本與取樣尚待確認。", data: "資料來源與權限尚待確認。", analysis: "分析策略尚待確認。", ethics: "不得推定倫理核准；尚待正式審查。", privacy: "個資、授權與最小化方案尚待確認。", risks: "證據不足可能造成過度主張。", alternatives: "若資料不可得，縮小範圍並保留 UNKNOWN。", nstcNarrative: "依問題、目標、策略、行動、里程碑與效益形成合成 CM03 式結構；非官方格式。", preliminaryEvidence: "目前只記錄待補證據，不推定初步成果存在。", feasibility: "可行性需連結資料、團隊、時程與風險。", expectedOutputs: "可追溯的研究產出。", courseContext: "課程與學生脈絡尚待確認。", teachingProblem: "教學問題尚待實證界定。", intervention: "教學介入尚待設計。", learningOutcomes: "學習成效指標尚待確認。", evaluationDesign: "評量與比較設計尚待確認。", implementationFidelity: "實施忠實度紀錄尚待設計。", teachingArtifacts: "教學產物尚待列舉。", reflectionPlan: "反思循環尚待設計。", workPackageTitle: "WP1 合成工作包", workPackageObjective: "完成可驗證的問題、方法與證據鏈。", workPackageMethods: "依固定契約逐項核對並保留未解事項。", startMonth: "1", endMonth: "12", milestone: "完成一份人工核對的固定版本。", milestoneMonth: "12", kpiMeasure: "固定版本與要求矩陣完整度", kpiTarget: "所有官方事實為 PASS 或 NA", kpiEvidence: "Human Gate 綁定的內容雜湊", teamRole: "計畫主持與研究設計", teamResponsibility: "核對官方來源與研究內容。", teamContribution: "負責問題、方法、預算與風險的一致性。", resources: "既有研究環境與合規資料來源", budgetCategory: "OPERATING", budgetUnit: "項", budgetQuantity: "1", budgetUnitCost: "0", budgetJustification: "合成零額範例；正式金額與必要性必須依工作包及年度規則更新。", budgetRuleStatus: "UNKNOWN", attachmentStatus: "UNKNOWN", unresolvedIssues: "當年度官方規則、期限、格式、預算與附件均待核對。", approvalRationale: "", approvalConfirmed: false };
}

function lines(value: string) { return value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); }
function requestKey(prefix: string) { return `${prefix}:${crypto.randomUUID()}`; }
async function sha(value: unknown) { const bytes = new TextEncoder().encode(JSON.stringify(value)); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join(""); }

export default function ProposalStudio({ projectId }: { projectId: string }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [form, setForm] = useState<FormState>(initialForm); const [requirementState, setRequirementState] = useState<Record<string, RequirementStatus>>(() => Object.fromEntries(requirements.NSTC_RESEARCH.map((item) => [item.category, "UNKNOWN"]))); const [activeId, setActiveId] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [exportBody, setExportBody] = useState(""); const [modeProfile, setModeProfile] = useState<ModelModeProfile>("AUTO"); const [guidanceFocus, setGuidanceFocus] = useState<GuidanceFocus>("STRUCTURE"); const [guidanceSuggestions, setGuidanceSuggestions] = useState<GuidanceSuggestion[]>([]); 
  const versions = useMemo(() => workspace?.proposals.filter((item) => item.proposal.mode === form.mode) ?? [], [workspace, form.mode]); const active = versions.find((item) => item.documentVersionId === activeId) ?? versions[0] ?? null; const previous = active ? versions.find((item) => item.logicalId === active.logicalId && item.versionNumber === active.versionNumber - 1) ?? null : null;
  const source = workspace?.sources.find((item) => item.documentVersionId === form.sourceId) ?? null;
  const quantity = Math.max(1, Number.parseInt(form.budgetQuantity, 10) || 1); const unitCost = Math.max(0, Number.parseInt(form.budgetUnitCost, 10) || 0); const subtotal = quantity * unitCost;
  const logicalId = form.mode === "NSTC_RESEARCH" ? "m05-nstc-proposal-main" : "m05-moe-proposal-main"; const expectedVersion = Math.max(0, ...versions.filter((item) => item.logicalId === logicalId).map((item) => item.versionNumber));
  const blocking = active ? active.validation.factualFail + active.validation.factualUnknown + active.validation.unresolvedCount + (active.validation.sourceFreshness === "CURRENT" ? 0 : 1) : 1;

  function update<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function setMode(mode: ProposalMode) { setForm((current) => ({ ...current, mode, sourceVerified: false, budgetRuleStatus: "UNKNOWN", attachmentStatus: "UNKNOWN", approvalConfirmed: false })); setRequirementState(Object.fromEntries(requirements[mode].map((item) => [item.category, "UNKNOWN"]))); setActiveId(""); setExportBody(""); }
  async function load() { setError(""); try { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/proposal-studio`, { cache: "no-store" }); const data = await response.json() as { ok?: boolean; workspace?: Workspace; error?: string }; if (!response.ok || !data.ok || !data.workspace) throw new Error(data.error || "無法載入計畫書工作室。"); setWorkspace(data.workspace); setForm((current) => ({ ...current, sourceId: current.sourceId || data.workspace?.sources[0]?.documentVersionId || "" })); setActiveId((current) => current || data.workspace?.proposals[0]?.documentVersionId || ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "無法載入計畫書工作室。"); } }
  useEffect(() => { void load(); }, [projectId]);
  useEffect(() => { setGuidanceSuggestions([]); }, [activeId]);
  useEffect(() => { setGuidanceSuggestions([]); }, [activeId]);
  useEffect(() => { setGuidanceSuggestions([]); }, [activeId]);
  async function post(body: Record<string, unknown>) { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}/proposal-studio`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json() as { ok?: boolean; error?: string; [key: string]: unknown }; if (!response.ok || !data.ok) throw new Error(data.error || "操作未通過固定計畫書契約。"); return data; }

  async function buildProposal(): Promise<ProposalDraft> {
    const sourceHash = await sha({ sourceUrl: form.sourceUrl, effectiveYear: Number(form.effectiveYear), retrievedDate: form.retrievedDate, requirements: requirementState });
    const common = { mode: form.mode, callProgram: { programName: form.programName, programCode: null, effectiveYear: Number(form.effectiveYear) }, officialSource: { sourceUrl: form.sourceUrl, authorityClass: form.mode === "NSTC_RESEARCH" ? "NSTC_OFFICIAL" as const : "MOE_OFFICIAL" as const, retrievedAt: `${form.retrievedDate}T12:00:00.000Z`, effectiveYear: Number(form.effectiveYear), sourceHash, humanVerified: form.sourceVerified }, bilingual: { titleZhTw: form.titleZhTw, titleEn: form.titleEn, abstractZhTw: form.abstractZhTw, abstractEn: form.abstractEn, keywordsZhTw: lines(form.keywordsZhTw), keywordsEn: lines(form.keywordsEn) }, narrative: { problem: form.problem, background: form.background, literatureGap: form.literatureGap, aims: lines(form.aims), researchQuestions: lines(form.questions), hypotheses: lines(form.hypotheses), innovation: form.innovation, significance: form.significance, expectedImpact: form.impact, methods: form.methods, sample: form.sample, data: form.data, analysis: form.analysis, ethics: form.ethics, privacy: form.privacy, risks: lines(form.risks), alternatives: lines(form.alternatives) }, workPackages: [{ workPackageId: "wp-001", title: form.workPackageTitle, objective: form.workPackageObjective, methods: form.workPackageMethods, startMonth: Number(form.startMonth), endMonth: Number(form.endMonth) }], milestones: [{ milestoneId: "milestone-001", workPackageId: "wp-001", dueMonth: Number(form.milestoneMonth), deliverable: form.milestone }], kpis: [{ kpiId: "kpi-001", workPackageId: "wp-001", measure: form.kpiMeasure, target: form.kpiTarget, evidencePlan: form.kpiEvidence }], team: [{ roleId: "role-001", role: form.teamRole, responsibility: form.teamResponsibility, contribution: form.teamContribution }], resources: lines(form.resources), budget: { currency: "TWD" as const, items: [{ itemId: "budget-001", category: form.budgetCategory, unit: form.budgetUnit, quantity, unitCostTwd: unitCost, subtotalTwd: subtotal, justification: form.budgetJustification, workPackageId: "wp-001", ruleEvidenceStatus: form.budgetRuleStatus }], totalTwd: subtotal }, requirements: requirements[form.mode].map((item) => ({ category: item.category, status: requirementState[item.category] ?? "UNKNOWN", officialRule: `${item.label}：請依當年度官方來源逐項核對；本機不提供常年有效數值。`, evidence: requirementState[item.category] === "PASS" ? "研究者已人工比對固定官方來源。" : requirementState[item.category] === "NA" ? "研究者判定不適用並保留理由。" : "尚無足夠官方證據。", remediation: "回到當年度官方來源核對並更新固定來源雜湊。", sourceHash })), attachments: [{ attachmentId: "attachment-001", label: "當年度官方附件清單（合成占位）", required: true, status: form.attachmentStatus, evidence: form.attachmentStatus === "PASS" ? "研究者已逐項人工核對。" : "尚待依當年度官方來源核對。" }], unresolvedIssues: lines(form.unresolvedIssues) };
    return { ...common, modeSpecific: form.mode === "NSTC_RESEARCH" ? { kind: "NSTC_RESEARCH", cm03Narrative: form.nstcNarrative, preliminaryEvidence: form.preliminaryEvidence, feasibility: form.feasibility, expectedOutputs: lines(form.expectedOutputs) } : { kind: "MOE_TEACHING_PRACTICE", courseContext: form.courseContext, teachingProblem: form.teachingProblem, intervention: form.intervention, learningOutcomes: lines(form.learningOutcomes), evaluationDesign: form.evaluationDesign, implementationFidelity: form.implementationFidelity, teachingArtifacts: lines(form.teachingArtifacts), reflectionPlan: form.reflectionPlan } };
  }

  async function save(event: FormEvent) { event.preventDefault(); setBusy("save"); setError(""); setNotice(""); try { const proposal = await buildProposal(); const data = await post({ operation: "SAVE_PROPOSAL_VERSION", idempotencyKey: requestKey("m05-save"), logicalId, expectedVersion, title: form.titleZhTw, sourceDocumentVersionId: source?.documentVersionId ?? null, sourceContentHash: source?.contentHash ?? null, proposal }); const saved = data.proposal as ProposalVersion; await load(); setActiveId(saved.documentVersionId); setNotice("已新增結構化 append-only 計畫書版本；既有 M03/M04 與來源文件未覆寫。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "計畫書版本未儲存。"); } finally { setBusy(""); } }
  async function approve() { if (!active) return; setBusy("approve"); setError(""); setNotice(""); try { await post({ operation: "APPROVE_PROPOSAL", idempotencyKey: requestKey("m05-approve"), documentVersionId: active.documentVersionId, contentHash: active.contentHash, rationale: form.approvalRationale }); update("approvalConfirmed", false); await load(); setNotice("DOCUMENT_RELEASE Human Gate 已綁定此計畫書版本的精確內容雜湊。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Human Gate 未完成。"); } finally { setBusy(""); } }
  async function preview(format: "JSON" | "MARKDOWN") { if (!active?.humanGate.id) return; setBusy("export"); setError(""); try { const data = await post({ operation: "EXPORT_PROPOSAL_PREVIEW", documentVersionId: active.documentVersionId, contentHash: active.contentHash, humanGateId: active.humanGate.id, format }); setExportBody((data.preview as { body: string }).body); } catch (caught) { setError(caught instanceof Error ? caught.message : "預覽未產生。"); } finally { setBusy(""); } }
  async function requestGuidance() { if (!active) return; setBusy("guidance"); setError(""); setNotice(""); try { const data = await post({ operation: "REQUEST_PROPOSAL_GUIDANCE", idempotencyKey: requestKey("m05-guidance"), documentVersionId: active.documentVersionId, contentHash: active.contentHash, focus: guidanceFocus, modeProfile }); setGuidanceSuggestions((data.guidance as { suggestions: GuidanceSuggestion[] }).suggestions); setNotice("已取得老麥建議（尚未驗證）；不會寫入正式計畫書。"); } catch (caught) { setError(caught instanceof Error ? caught.message : "老麥建議未取得。"); } finally { setBusy(""); } }

  return <section className="v13-panel m05-studio" aria-labelledby="m05-title">
    <div className="v13-panel-head"><div><p className="section-kicker">M05 · 臺灣計畫書工作室</p><h2 id="m05-title">臺灣計畫書工作室</h2></div><p className="v13-panel-note">兩種模式共用結構化核心；年度規則只能以人工核對的官方來源為準。</p></div>
    <div className="m05-notice">合成範例、技能範本與老麥建議都不是 NSTC 或教育部的官方事實。頁數、門檻、期限、時數與經費上限一律不得視為常年有效；正式提升前必須完成來源新鮮度檢查與精確 Human Gate。</div>
    {error && <div className="v13-error" role="alert">{error}</div>}{notice && <div className="v13-success" role="status">{notice}</div>}
    <div className="m05-mode" role="group" aria-label="計畫模式">{(["NSTC_RESEARCH", "MOE_TEACHING_PRACTICE"] as ProposalMode[]).map((mode) => <button type="button" key={mode} className={form.mode === mode ? "active" : ""} onClick={() => setMode(mode)}>{modeLabels[mode]}</button>)}</div>
    <form className="m05-form" onSubmit={save}>
      <section><h3>計畫別與官方來源</h3><div className="m05-grid"><label>計畫／徵件名稱<input value={form.programName} onChange={(event) => update("programName", event.target.value)} maxLength={500} required /></label><label>有效年度<input type="number" min="2000" max="2200" value={form.effectiveYear} onChange={(event) => update("effectiveYear", event.target.value)} required /></label><label>來源擷取日期<input type="date" value={form.retrievedDate} onChange={(event) => update("retrievedDate", event.target.value)} required /></label></div><label>官方來源 URL<input type="url" value={form.sourceUrl} onChange={(event) => update("sourceUrl", event.target.value)} maxLength={2000} required /></label><label>既有 RESEARCH_PLAN 來源<select value={form.sourceId} onChange={(event) => update("sourceId", event.target.value)}><option value="">不綁定既有版本</option>{workspace?.sources.map((item) => <option key={item.documentVersionId} value={item.documentVersionId}>{item.title} · v{item.versionNumber}</option>)}</select></label><label className="m05-check"><input type="checkbox" checked={form.sourceVerified} onChange={(event) => update("sourceVerified", event.target.checked)} />我已人工核對當年度官方來源；此確認不會自動把 UNKNOWN 改為 PASS。</label></section>
      <section><h3>雙語標題、摘要與關鍵字</h3><div className="m05-two"><label>中文標題<input value={form.titleZhTw} onChange={(event) => update("titleZhTw", event.target.value)} required /></label><label>English title<input value={form.titleEn} onChange={(event) => update("titleEn", event.target.value)} required /></label><label>中文摘要<textarea rows={6} value={form.abstractZhTw} onChange={(event) => update("abstractZhTw", event.target.value)} required /></label><label>English abstract<textarea rows={6} value={form.abstractEn} onChange={(event) => update("abstractEn", event.target.value)} required /></label><label>中文關鍵字（每行一個）<textarea rows={3} value={form.keywordsZhTw} onChange={(event) => update("keywordsZhTw", event.target.value)} required /></label><label>English keywords (one per line)<textarea rows={3} value={form.keywordsEn} onChange={(event) => update("keywordsEn", event.target.value)} required /></label></div><OldMikeAssistGroupControl projectId={projectId} surface="M05_BILINGUAL" groupId="m05-bilingual" value={{ titleZhTw: form.titleZhTw, titleEn: form.titleEn, abstractZhTw: form.abstractZhTw, abstractEn: form.abstractEn, keywordsZhTw: form.keywordsZhTw, keywordsEn: form.keywordsEn }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /></section>
      <section><h3>問題、證據、方法與風險</h3><div className="m05-two">{([ ["problem", "研究／教學問題"], ["background", "背景"], ["literatureGap", "文獻缺口"], ["aims", "目標（每行一項）"], ["questions", "研究問題（每行一項）"], ["hypotheses", "假設（每行一項，可留空但需保留結構）"], ["innovation", "創新"], ["significance", "重要性"], ["impact", "預期影響"], ["methods", "方法"], ["sample", "樣本"], ["data", "資料"], ["analysis", "分析"], ["ethics", "倫理"], ["privacy", "隱私"], ["risks", "風險（每行一項）"], ["alternatives", "替代方案（每行一項）"] ] as Array<[keyof FormState,string]>).map(([key,label]) => <label key={key}>{label}<textarea rows={3} value={String(form[key])} onChange={(event) => update(key, event.target.value as never)} required={key !== "hypotheses"} /></label>)}</div><OldMikeAssistGroupControl projectId={projectId} surface="M05_RATIONALE" groupId="m05-rationale" value={{ problem: form.problem, background: form.background, literatureGap: form.literatureGap, aims: form.aims, questions: form.questions, hypotheses: form.hypotheses, innovation: form.innovation, significance: form.significance, impact: form.impact }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /><OldMikeAssistGroupControl projectId={projectId} surface="M05_METHODS" groupId="m05-methods" value={{ methods: form.methods, sample: form.sample, data: form.data, analysis: form.analysis, ethics: form.ethics, privacy: form.privacy, risks: form.risks, alternatives: form.alternatives }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /></section>
      <section><h3>{form.mode === "NSTC_RESEARCH" ? "NSTC 模式結構" : "教育部教學實踐模式結構"}</h3>{form.mode === "NSTC_RESEARCH" ? <div className="m05-two"><label>CM03 式研究敘事（結構協助，非官方格式）<textarea rows={6} value={form.nstcNarrative} onChange={(event) => update("nstcNarrative", event.target.value)} required /></label><label>初步證據<textarea rows={6} value={form.preliminaryEvidence} onChange={(event) => update("preliminaryEvidence", event.target.value)} required /></label><label>可行性<textarea rows={4} value={form.feasibility} onChange={(event) => update("feasibility", event.target.value)} required /></label><label>預期產出（每行一項）<textarea rows={4} value={form.expectedOutputs} onChange={(event) => update("expectedOutputs", event.target.value)} required /></label></div> : <div className="m05-two">{([ ["courseContext", "課程脈絡"], ["teachingProblem", "教學問題"], ["intervention", "介入／設計"], ["learningOutcomes", "學習成效（每行一項）"], ["evaluationDesign", "資料與評量設計"], ["implementationFidelity", "實施忠實度"], ["teachingArtifacts", "教學產物（每行一項）"], ["reflectionPlan", "反思計畫"] ] as Array<[keyof FormState,string]>).map(([key,label]) => <label key={key}>{label}<textarea rows={4} value={String(form[key])} onChange={(event) => update(key, event.target.value as never)} required /></label>)}</div>}<OldMikeAssistGroupControl projectId={projectId} surface="M05_MODE_SPECIFIC" groupId={form.mode === "NSTC_RESEARCH" ? "m05-mode-nstc" : "m05-mode-moe"} value={form.mode === "NSTC_RESEARCH" ? { nstcNarrative: form.nstcNarrative, preliminaryEvidence: form.preliminaryEvidence, feasibility: form.feasibility, expectedOutputs: form.expectedOutputs } : { courseContext: form.courseContext, teachingProblem: form.teachingProblem, intervention: form.intervention, learningOutcomes: form.learningOutcomes, evaluationDesign: form.evaluationDesign, implementationFidelity: form.implementationFidelity, teachingArtifacts: form.teachingArtifacts, reflectionPlan: form.reflectionPlan }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /></section>
      <section><h3>工作包、里程碑、KPI、團隊與資源</h3><div className="m05-three"><label>工作包標題<input value={form.workPackageTitle} onChange={(event) => update("workPackageTitle", event.target.value)} required /></label><label>起始月<input type="number" min="1" max="120" value={form.startMonth} onChange={(event) => update("startMonth", event.target.value)} required /></label><label>結束月<input type="number" min="1" max="120" value={form.endMonth} onChange={(event) => update("endMonth", event.target.value)} required /></label></div><div className="m05-two"><label>工作包目標<textarea value={form.workPackageObjective} onChange={(event) => update("workPackageObjective", event.target.value)} required /></label><label>工作包方法<textarea value={form.workPackageMethods} onChange={(event) => update("workPackageMethods", event.target.value)} required /></label><label>里程碑<textarea value={form.milestone} onChange={(event) => update("milestone", event.target.value)} required /></label><label>里程碑月份<input type="number" min="1" max="120" value={form.milestoneMonth} onChange={(event) => update("milestoneMonth", event.target.value)} required /></label><label>KPI 衡量<input value={form.kpiMeasure} onChange={(event) => update("kpiMeasure", event.target.value)} required /></label><label>KPI 目標<input value={form.kpiTarget} onChange={(event) => update("kpiTarget", event.target.value)} required /></label><label>KPI 證據計畫<textarea value={form.kpiEvidence} onChange={(event) => update("kpiEvidence", event.target.value)} required /></label><label>團隊角色<input value={form.teamRole} onChange={(event) => update("teamRole", event.target.value)} required /></label><label>責任<textarea value={form.teamResponsibility} onChange={(event) => update("teamResponsibility", event.target.value)} required /></label><label>貢獻<textarea value={form.teamContribution} onChange={(event) => update("teamContribution", event.target.value)} required /></label><label>資源（每行一項）<textarea value={form.resources} onChange={(event) => update("resources", event.target.value)} required /></label></div><OldMikeAssistGroupControl projectId={projectId} surface="M05_EXECUTION" groupId="m05-execution" value={{ workPackageTitle: form.workPackageTitle, workPackageObjective: form.workPackageObjective, workPackageMethods: form.workPackageMethods, milestone: form.milestone, kpiMeasure: form.kpiMeasure, kpiTarget: form.kpiTarget, kpiEvidence: form.kpiEvidence, teamRole: form.teamRole, teamResponsibility: form.teamResponsibility, teamContribution: form.teamContribution, resources: form.resources }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /></section>
      <section><h3>預算算術與工作包連結</h3><div className="m05-budget"><label>類別<select value={form.budgetCategory} onChange={(event) => update("budgetCategory", event.target.value as BudgetCategory)}>{["PERSONNEL","OPERATING","EQUIPMENT","TRAVEL","OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label><label>單位<input value={form.budgetUnit} onChange={(event) => update("budgetUnit", event.target.value)} required /></label><label>數量<input type="number" min="1" value={form.budgetQuantity} onChange={(event) => update("budgetQuantity", event.target.value)} required /></label><label>單價（TWD）<input type="number" min="0" value={form.budgetUnitCost} onChange={(event) => update("budgetUnitCost", event.target.value)} required /></label><output>小計：{subtotal.toLocaleString("zh-TW")} TWD</output><label>規則證據<select value={form.budgetRuleStatus} onChange={(event) => update("budgetRuleStatus", event.target.value as RequirementStatus)}>{Object.entries(statusLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><label>必要性與工作包理由<textarea rows={3} value={form.budgetJustification} onChange={(event) => update("budgetJustification", event.target.value)} required /></label></section>
      <section className="m05-requirements"><h3>當年度官方要求矩陣</h3><p>每列只記錄事實判定；老麥的結構／方法建議不會寫入此矩陣。</p>{requirements[form.mode].map((item) => <article key={item.category}><strong>{item.label}</strong><select aria-label={`${item.label}狀態`} value={requirementState[item.category] ?? "UNKNOWN"} onChange={(event) => setRequirementState((current) => ({ ...current, [item.category]: event.target.value as RequirementStatus }))}>{Object.entries(statusLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select><small>來源規則與證據會綁定此官方來源雜湊。</small></article>)}</section>
      <section><h3>附件、未解事項與儲存</h3><div className="m05-two"><label>必要附件狀態<select value={form.attachmentStatus} onChange={(event) => update("attachmentStatus", event.target.value as RequirementStatus)}>{Object.entries(statusLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>未解事項（每行一項；全部解決後留空）<textarea rows={4} value={form.unresolvedIssues} onChange={(event) => update("unresolvedIssues", event.target.value)} /></label></div><OldMikeAssistGroupControl projectId={projectId} surface="M05_BUDGET_RISKS" groupId="m05-budget-risks" value={{ budgetJustification: form.budgetJustification, unresolvedIssues: form.unresolvedIssues }} onApply={(value) => setForm((current) => ({ ...current, ...value }))} /><button type="submit" className="primary-button" data-testid="m05-save" disabled={busy !== ""}>{busy === "save" ? "儲存中…" : "新增計畫書版本（不覆寫）"}</button></section>
    </form>

    <section className="m05-versions"><div className="m03-section-head"><div><p className="section-kicker">僅附加 · 並排</p><h3>版本、要求失敗與來源新鮮度</h3></div>{versions.length ? <select aria-label="計畫書版本" value={active?.documentVersionId ?? ""} onChange={(event) => setActiveId(event.target.value)}>{versions.map((item) => <option value={item.documentVersionId} key={item.documentVersionId}>v{item.versionNumber} · {item.title}</option>)}</select> : null}</div>{!active ? <div className="v13-empty"><Icon name="file" /><div><strong>尚無 M05 計畫書版本</strong><p>第一個版本可以保留 UNKNOWN；只有 Human Gate 之前必須全部解決。</p></div></div> : <><div className="m05-status"><span>來源 {active.validation.sourceFreshness}</span><span>PASS {active.validation.factualPass}</span><span>FAIL {active.validation.factualFail}</span><span>UNKNOWN {active.validation.factualUnknown}</span><span>未解 {active.validation.unresolvedCount}</span><span>預算 {active.validation.totalTwd.toLocaleString("zh-TW")} TWD</span></div><div className="m05-side"><article><h4>目前 v{active.versionNumber}</h4><strong>{active.proposal.bilingual.titleZhTw}</strong><p>{active.proposal.bilingual.abstractZhTw}</p></article><article><h4>{previous ? `前一版 v${previous.versionNumber}` : "前一版"}</h4>{previous ? <><strong>{previous.proposal.bilingual.titleZhTw}</strong><p>{previous.proposal.bilingual.abstractZhTw}</p></> : <p>尚無前一版；來源文件仍保持不變。</p>}</article><article><h4>差異與風險</h4><p>{previous && previous.contentHash !== active.contentHash ? "內容雜湊已改變；核准必須重新綁定目前版本。" : "目前沒有可比較的前一版。"}</p><p>官方來源：{active.proposal.officialSource.humanVerified ? "人工已核對" : "尚未人工核對"}</p></article></div><div className="m05-guidance"><strong>老麥建議・尚未驗證</strong><p>老麥只會把建議套到目前尚未儲存的本機草稿；新增版本與 Human Gate 仍由研究者明確操作。先儲存目前版本，再對該版本取得建議。</p><ModelModePicker operation="PROPOSAL_GUIDANCE" value={modeProfile} onChange={setModeProfile} testId="m05-model-mode" /><div className="m05-guidance-controls"><select aria-label="建議焦點" value={guidanceFocus} onChange={(event) => setGuidanceFocus(event.target.value as GuidanceFocus)}>{Object.entries(focusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button type="button" className="secondary-button" onClick={() => void requestGuidance()} disabled={busy !== ""}>{busy === "guidance" ? "取得中…" : "取得老麥建議（目前版本）"}</button></div>{guidanceSuggestions.length > 0 && <div className="m05-guidance-suggestions">{guidanceSuggestions.map((item) => <article key={item.suggestionId}><strong>{focusLabels[item.focus]}</strong><p>{item.explanation}</p><p>風險：{item.risk}</p><p>行動：{item.action}</p></article>)}</div>}</div></>}
    </section>

    {active && <section className="m05-human-gate"><div><p className="section-kicker">文件釋出 · 精確內容雜湊</p><h3>Human Gate 與本機預覽</h3><p>只有當年度官方來源為 CURRENT 且人工核對、FAIL/UNKNOWN/未解事項為零、預算與附件通過時，才能綁定此精確版本。這不會送件、寄信或上傳。</p><div className="m05-status"><span>阻擋項 {blocking}</span><span>{active.humanGate.status}</span></div></div>{active.humanGate.status === "REQUIRED" ? <div><label>核准理由<textarea aria-label="計畫書核准理由" rows={4} value={form.approvalRationale} onChange={(event) => update("approvalRationale", event.target.value)} /></label><label className="m05-check"><input type="checkbox" checked={form.approvalConfirmed} onChange={(event) => update("approvalConfirmed", event.target.checked)} />我已核對官方來源、要求矩陣、研究內容、預算、附件、未解事項與此精確內容雜湊。</label><button type="button" className="primary-button" onClick={() => void approve()} disabled={busy !== "" || blocking > 0 || !form.approvalConfirmed || form.approvalRationale.trim().length < 8}>{busy === "approve" ? "核准中…" : "核准此固定計畫書版本"}</button></div> : <div><p className="m05-approved"><Icon name="shield" size={18} />此版本已通過精確 Human Gate。</p><div className="m05-export-actions"><button type="button" className="secondary-button" onClick={() => void preview("JSON")} disabled={busy !== ""}>JSON 預覽</button><button type="button" className="secondary-button" onClick={() => void preview("MARKDOWN")} disabled={busy !== ""}>Markdown 預覽</button></div></div>}</section>}
    {exportBody && <section className="m05-export"><h3>本機預覽（不送件）</h3><pre tabIndex={0} aria-label="計畫書本機預覽內容">{exportBody}</pre></section>}
  </section>;
}
