export const TOPIC_LAB_PROVIDER_TIMEOUT_MS = 300_000 as const;
export const TOPIC_LAB_UAT_TIMEOUT_MS = 315_000 as const;
export const TOPIC_LAB_OUTPUT_LIMIT_BYTES = 192_000 as const;
export const RESEARCH_START_STAGE_PROVIDER_TIMEOUT_MS = 300_000 as const;
export const RESEARCH_START_STAGE_BROWSER_TIMEOUT_MS = RESEARCH_START_STAGE_PROVIDER_TIMEOUT_MS + 15_000;
export const RESEARCH_START_STAGE_OUTPUT_LIMIT_BYTES = 24 * 1_024;
