#!/usr/bin/env python3
"""
render-fixtures-v41.py — C10/C11 三目標 fixture 文件（DOCX + PDF）
生成 6 份隔離示例：JOURNAL_EN、NSTC_TC、MOE_TC，各 DOCX + PDF。
所有資料為合成 fixture，明示非真實送件文件。不含 IRB/署名同意/接受紀錄。

Renderer: python-docx 1.2.0 (OOXML) + reportlab 5.0.1 (PDF)
字型：Noto Sans CJK TC（Google 開源，僅供渲染暫存，不隨交付包分發）
"""
import os, json, hashlib, datetime
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle as PS

OUT = "/home/node/dev/repo/tmp-v41-fixture"
FONT_DIR = "/tmp/v41-qa/fonts"
os.makedirs(OUT, exist_ok=True)

# 註冊 CJK 字型（僅運行時使用，不打包進交付）
pdfmetrics_registered = False
def register_cjk():
    global pdfmetrics_registered
    if pdfmetrics_registered: return
    from reportlab.pdfbase import pdfmetrics
    pdfmetrics.registerFont(TTFont("NotoTC", f"{FONT_DIR}/NotoSansTC-Regular.ttf"))
    pdfmetrics.registerFont(TTFont("NotoTC-Bold", f"{FONT_DIR}/NotoSansTC-Bold.ttf"))
    pdfmetrics_registered = True

FIXTURE_DISCLAIMER = {
    "en": "SYNTHETIC FIXTURE — For platform export QA only. Not a real submission. No IRB approval, author consent, or research outcome is claimed.",
    "tc": "合成示範文件 — 供平台匯出功能驗收之用，非真實送件文件。本檔不宣稱任何真實倫理核准、受試者同意、研究成果或接受紀錄。",
}

# 合成 fixture 數據（與 verify-stat-engine-reference.mjs 相同來源，已對 scipy 驗證）
WELCH = {"n1": 3, "n2": 3, "t": -11.934, "df": 2.828, "p": 0.001668, "ci": [-1165.184, -661.015], "d": -9.744}
ANCOVA = {"b1": -945.213, "se": 107.755, "t": -8.772, "p": 0.072263, "r2": 0.991, "ci": [-2314.372, 423.947]}

def set_doc_defaults(doc, font="Times New Roman", cjk=False):
    st = doc.styles["Normal"]
    st.font.name = font
    st.font.size = Pt(11)
    if cjk:
        # OOXML 東亞字型設定
        from docx.oxml.ns import qn
        rpr = st.element.get_or_add_rPr()
        rFonts = rpr.find(qn("w:rFonts"))
        if rFonts is None:
            from docx.oxml import OxmlElement
            rFonts = OxmlElement("w:rFonts"); rpr.append(rFonts)
        rFonts.set(qn("w:eastAsia"), "Noto Sans CJK TC")

def add_title(doc, text, en=False):
    p = doc.add_heading(text, level=0)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return p

def add_para(doc, text, bold=False):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    return p

def make_docx(goal, lang):
    doc = Document()
    if lang == "en":
        set_doc_defaults(doc, font="Times New Roman")
        add_title(doc, "Synthetic Fixture: VR-Based Scaffolding Effects on Reaction Time")
        doc.add_paragraph(FIXTURE_DISCLAIMER["en"]).runs[0].italic = True
        doc.add_heading("Abstract", level=1)
        doc.add_paragraph("Synthetic fixture abstract. Mean RT decreased in the intervention group (T1 M=1860.23, SD=56.86) relative to control (T1 M=2773.33, SD=126.65). Welch t(2.83) = −11.934, p = 0.0017, Cohen's d = −9.74, 95% CI [−1165.18, −661.02].")
        doc.add_heading("1. Introduction", level=1)
        doc.add_paragraph("Synthetic fixture introduction paragraph. This document is generated by the platform renderer for export QA purposes only.")
        doc.add_heading("2. Method", level=1)
        doc.add_paragraph("Synthetic cohort: n=6 (3 per arm). Reaction time in milliseconds measured at pretest (T0) and posttest (T1).")
        doc.add_heading("3. Results", level=1)
        t = doc.add_table(rows=3, cols=4)
        t.style = "Light Grid Accent 1"
        hdr = t.rows[0].cells
        hdr[0].text = "Statistic"; hdr[1].text = "Value"; hdr[2].text = "95% CI"; hdr[3].text = "p"
        rows = [
            ("Welch t", f"t(2.83) = {WELCH['t']:.3f}", f"[{WELCH['ci'][0]:.2f}, {WELCH['ci'][1]:.2f}]", f"{WELCH['p']:.4f}"),
            ("ANCOVA b1", f"β = {ANCOVA['b1']:.3f}, SE = {ANCOVA['se']:.2f}", f"[{ANCOVA['ci'][0]:.2f}, {ANCOVA['ci'][1]:.2f}]", f"{ANCOVA['p']:.4f}"),
        ]
        for i, row in enumerate(rows, start=1):
            for j, v in enumerate(row):
                t.rows[i].cells[j].text = v
        doc.add_paragraph("Cohen's d = −9.74. η² (ANCOVA R²) = 0.99. α = 0.05. Holm-Bonferroni adjusted.")
        doc.add_heading("4. Discussion", level=1)
        doc.add_paragraph("Synthetic fixture discussion. Reference: Smith, J. (2024). Synthetic Citation for QA. Journal of Fixture Studies, 1(1), 1–10.")
        doc.add_heading("References", level=1)
        doc.add_paragraph("Smith, J. (2024). Synthetic Citation for QA. Journal of Fixture Studies, 1(1), 1–10.")
    else:
        set_doc_defaults(doc, font="Noto Sans TC", cjk=True)
        title = "合成示範：VR 鷹架引導對反應時間之影響" if goal == "NSTC_TC" else "合成示範：AI 適應介入對學習成效之影響"
        add_title(doc, title)
        doc.add_paragraph(FIXTURE_DISCLAIMER["tc"]).runs[0].italic = True
        doc.add_heading("壹、研究背景與動機", level=1)
        doc.add_paragraph("本檔為合成示範文件。研究背景段落旨在驗證繁體中文字、α/β/η²、±、≤、≥、負號、小數位與單位（ms）之渲染保真度。")
        doc.add_heading("貳、科學問題與工作包" if goal == "NSTC_TC" else "貳、課程問題與學習成果", level=1)
        doc.add_paragraph("合成工作包 WP-1：驗證跨頁表格、公式（β1 = −945.21, SE = 107.76）與上下標之呈現。" if goal == "NSTC_TC" else "合成課程介入：驗證學習成果表與評量指標之呈現。")
        doc.add_heading("參、預期結果與數值", level=1)
        t = doc.add_table(rows=3, cols=4)
        t.style = "Light Grid Accent 1"
        hdr = t.rows[0].cells
        hdr[0].text = "方法"; hdr[1].text = "數值"; hdr[2].text = "95% 信賴區間"; hdr[3].text = "p 值"
        rows = [
            ("Welch t 檢定", f"t(2.83) = {WELCH['t']:.3f}", f"[{WELCH['ci'][0]:.2f}, {WELCH['ci'][1]:.2f}]", f"{WELCH['p']:.4f}"),
            ("ANCOVA 迴歸係數 β1", f"β1 = {ANCOVA['b1']:.3f}, SE = {ANCOVA['se']:.2f}", f"[{ANCOVA['ci'][0]:.2f}, {ANCOVA['ci'][1]:.2f}]", f"{ANCOVA['p']:.4f}"),
        ]
        for i, row in enumerate(rows, start=1):
            for j, v in enumerate(row):
                t.rows[i].cells[j].text = v
        doc.add_paragraph("效果量 Cohen's d = −9.74；η² = 0.99；α = 0.05；Holm-Bonferroni 多重比較校正。")
        doc.add_heading("肆、限制與後續", level=1)
        doc.add_paragraph("本檔為合成示範，非真實研究資料。若以真實研究資料餵入，本平台之 renderer 仍以相同方式產出 DOCX/PDF。")
        doc.add_heading("參考文獻", level=1)
        doc.add_paragraph("王小明（2024）。合成引用範例。示範研究期刊，1(1), 1–10。")
    fp = f"{OUT}/fixture_{goal}.docx"
    doc.save(fp)
    return fp

def _ps(name, **kw):
    base = dict(fontName="NotoTC", fontSize=10, leading=14)
    base.update(kw)
    return PS(name=name, **base)

def make_pdf(goal, lang):
    register_cjk()
    fp = f"{OUT}/fixture_{goal}.pdf"
    doc = SimpleDocTemplate(fp, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    title_style = _ps("T", fontName="NotoTC-Bold", fontSize=16, leading=20)
    h_style = _ps("H", fontName="NotoTC-Bold", fontSize=12, leading=16)
    p_style = _ps("P")
    warn_style = _ps("W", fontSize=8, textColor=colors.grey)
    story = []
    if lang == "en":
        # Latin PDF via Helvetica is fine; but keep CJK-capable for symbols
        story.append(Paragraph("Synthetic Fixture: VR-Based Scaffolding Effects on Reaction Time", title_style))
        story.append(Paragraph(FIXTURE_DISCLAIMER["en"], warn_style)); story.append(Spacer(1, 12))
        story.append(Paragraph("Abstract", h_style))
        story.append(Paragraph("Synthetic fixture abstract. Mean RT decreased in intervention (T1 M=1860.23, SD=56.86) vs control (T1 M=2773.33, SD=122.75). Welch t(2.83) = −11.934, p = 0.0017, Cohen's d = −9.74, 95% CI [−1165.18, −661.02].", p_style))
        story.append(Paragraph("1. Introduction", h_style))
        story.append(Paragraph("Synthetic fixture introduction. Generated by platform renderer for export QA purposes only.", p_style))
        story.append(Paragraph("2. Method", h_style))
        story.append(Paragraph("Synthetic cohort: n=6 (3/arm), RT in ms, measured at T0 (pretest) and T1 (posttest).", p_style))
        story.append(Paragraph("3. Results", h_style))
        data = [["Statistic", "Value", "95% CI", "p"],
                ["Welch t-test", f"t(2.83) = {WELCH['t']:.3f}", f"[{WELCH['ci'][0]:.2f}, {WELCH['ci'][1]:.2f}]", f"{WELCH['p']:.4f}"],
                ["ANCOVA β1", f"β = {ANCOVA['b1']:.3f}, SE = {ANCOVA['se']:.2f}", f"[{ANCOVA['ci'][0]:.2f}, {ANCOVA['ci'][1]:.2f}]", f"{ANCOVA['p']:.4f}"]]
        tbl = Table(data, colWidths=[3.5*cm, 4.5*cm, 5*cm, 2*cm])
        tbl.setStyle(TableStyle([
            ("FONTNAME", (0,0), (-1,-1), "NotoTC"), ("FONTSIZE", (0,0), (-1,-1), 9),
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey), ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("ALIGN", (1,1), (-1,-1), "LEFT"),
        ]))
        story.append(tbl); story.append(Spacer(1, 10))
        story.append(Paragraph("Cohen's d = −9.74. R² (ANCOVA) = 0.99. α = 0.05. Holm-Bonferroni adjusted.", p_style))
        story.append(Paragraph("4. Discussion", h_style))
        story.append(Paragraph("Synthetic fixture discussion. Reference: Smith, J. (2024). Synthetic Citation for QA. Journal of Fixture Studies, 1(1), 1–10.", p_style))
        story.append(Paragraph("References", h_style))
        story.append(Paragraph("Smith, J. (2024). Synthetic Citation for QA. Journal of Fixture Studies, 1(1), 1–10.", p_style))
    else:
        title = "合成示範：VR 鷹架引導對反應時間之影響" if goal == "NSTC_TC" else "合成示範：AI 適應介入對學習成效之影響"
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(FIXTURE_DISCLAIMER["tc"], warn_style)); story.append(Spacer(1, 12))
        story.append(Paragraph("壹、研究背景", h_style))
        story.append(Paragraph("本檔為合成示範文件，驗證繁體中文、α/β/η²、±、≤、≥、負號、小數位與單位（ms）之渲染保真度。", p_style))
        story.append(Paragraph("貳、" + ("科學問題與工作包" if goal == "NSTC_TC" else "課程問題與學習成果"), h_style))
        story.append(Paragraph(("合成工作包 WP-1：驗證跨頁表格與 β1 = −945.21（SE = 107.76）之呈現。" if goal == "NSTC_TC" else "合成課程介入：驗證學習成果表與評量指標之呈現。"), p_style))
        story.append(Paragraph("參、預期結果", h_style))
        data = [["方法", "數值", "95% 信賴區間", "p 值"],
                ["Welch t 檢定", f"t(2.83) = {WELCH['t']:.3f}", f"[{WELCH['ci'][0]:.2f}, {WELCH['ci'][1]:.2f}]", f"{WELCH['p']:.4f}"],
                ["ANCOVA 係數 β1", f"β1 = {ANCOVA['b1']:.3f}, SE = {ANCOVA['se']:.2f}", f"[{ANCOVA['ci'][0]:.2f}, {ANCOVA['ci'][1]:.2f}]", f"{ANCOVA['p']:.4f}"]]
        tbl = Table(data, colWidths=[4*cm, 4.5*cm, 5*cm, 2*cm])
        tbl.setStyle(TableStyle([
            ("FONTNAME", (0,0), (-1,-1), "NotoTC"), ("FONTSIZE", (0,0), (-1,-1), 9),
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey), ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ]))
        story.append(tbl); story.append(Spacer(1, 10))
        story.append(Paragraph("效果量 Cohen's d = −9.74；η² = 0.99；α = 0.05；Holm-Bonferroni 多重比較校正。", p_style))
        story.append(Paragraph("肆、限制", h_style))
        story.append(Paragraph("本檔為合成示範，非真實研究資料；若以真實研究資料餵入，renderer 仍以相同方式產出。", p_style))
        story.append(Paragraph("參考文獻", h_style))
        story.append(Paragraph("王小明（2024）。合成引用範例。示範研究期刊，1(1), 1–10。", p_style))
    doc.build(story)
    return fp

def sha256(fp):
    h = hashlib.sha256()
    with open(fp, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""): h.update(chunk)
    return h.hexdigest()

def main():
    results = []
    goals = [("JOURNAL_EN", "en"), ("NSTC_TC", "tc"), ("MOE_TC", "tc")]
    for goal, lang in goals:
        for ext, maker in [("docx", make_docx), ("pdf", make_pdf)]:
            fp = maker(goal, lang)
            results.append({"goal": goal, "format": ext, "path": fp, "bytes": os.path.getsize(fp), "sha256": sha256(fp)})
    manifest = {
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "renderer": {"docx": "python-docx 1.2.0", "pdf": "reportlab 5.0.1", "font": "Noto Sans CJK TC (system, not redistributed)"},
        "fixture_data_source": "verify-stat-engine-reference.mjs (scipy-validated reference values)",
        "disclaimer": "All fixture documents are SYNTHETIC. Not real submissions. No IRB/consent/outcome claimed.",
        "files": results,
    }
    with open(f"{OUT}/render-manifest-v41.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    for r in results:
        print(f"{r['goal']}.{r['format']:4s} {r['bytes']:>8} bytes  sha256={r['sha256'][:16]}…")
    print(f"\nmanifest: {OUT}/render-manifest-v41.json")

if __name__ == "__main__":
    main()
